app:
    name: My App
    description: Welcome to ${app.name}


my:
   greeting: Hello World
   list:
       Value: One, Two, Three

db:
   connection: "{connectionString: 'http://___', userName:'Vamsi', password: 'Vamsi'}"
   host: 129.8.0.1
   port: 2400

management.endpoints.web.exposure.include: "*"
spring.profiles.active: test